version: '3.4'

x-app:
  &default-app
  image: hseeberger/scala-sbt:8u222_1.3.3_2.12.10
  command: sbt run
  working_dir: /app
  volumes:
    - "./:/app"
    - sbt-cousier-cache:/root/.cache/coursier
  environment:
    - APP_ENV=Local
    - LOG_LEVEL=Debug
  depends_on:
    - sqs
services:
  app:
    << : *default-app
  test:
    << : *default-app
    command: sbt clean coverage test coverageReport
  build:
    << : *default-app
    volumes:
      - "\$HOME/.sbt:/root/.sbt"
      - "./:/app"
      - sbt-cousier-cache:/root/.cache/coursier
    environment:
      - APP_BUILD_NUMBER
    command: sbt publish models/publish
  sqs:
    image: softwaremill/elasticmq
    ports:
      - 9324:9324
volumes:
  sbt-cousier-cache:
    external: true
